language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2


before_install:
  - wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
  - tar -xzvf dockerize-linux-amd64-v0.2.0.tar.gz
  - rm dockerize-linux-amd64-v0.2.0.tar.gz
  - ./dockerize -template vendor/docker/database.properties.tmpl:src/main/resources/database.properties
  - ./dockerize -template vendor/docker/log4j.xml.tmpl:src/main/resources/log4j.xml

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

before_script:
  - mysql -e 'create database oaip_test;'

script:
  - bundle exec middleman build -e $RACK_ENV
  - mvn clean test

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
